### ISSUE TITLE
No demo/demo_inference

### ISSUE THREAD

**Issue by csouflis** [ming71/RIDet#1]
Hello,

I wanted to run a demo with the pretrained model but there is no demo_inference.py in this repo. Can you upload it?

Thanks

**Comment by ming71** [comment]
Hello, the inference codes have been included [here](https://github.com/ming71/RIDet/blob/master/demo/demo_inference.py). And you can run `demo.sh` to obtain detections.

All these messages are mentioned in README.md, pls check it in detail.
