### ISSUE TITLE
No module named 'utils.nms.cpu_nms'

### ISSUE THREAD

**Issue by samwang90** [ming71/RIDet#3]
Hello,
nice job!

I followed instruction in pytorch branch. 
After run sh make.sh, cpu_nms.pyx does not appear in nms folder.
when i run demo.py, I found error No module named 'utils.nms.cpu_nms'

**Comment by ming71** [comment]
You should compile the source code about the NMS modules. Remove the *.o files, and then run make.sh to compile it.
