### ISSUE TITLE
the coordinate is negative

### ISSUE THREAD

**Issue by shenhaibb** [ming71/RIDet#4]
![B51F344D-47A3-439F-A2E0-6E521D3F0C00](https://user-images.githubusercontent.com/64736467/151179504-14f8d03f-8ed5-409c-97f8-3024ff9c64eb.png)
After using HRSC2DOTA.py, I notice that one of the coordinates is negative, why is it negative？

**Comment by ming71** [comment]
Thanks for your feedback, the five-parameter representation does not ensure that every point is within the image (i.e. positive). A few cases like this do not affect performance, and dataloader will truncate out-of-bounds edges.
